# -*- coding: utf-8 -*-
NOEMIE = { '000': { 'description': 'En-tête',
           'name': '000',
           'rang': '1',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '000'},
                         { 'name': "Type d'émetteur",
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'emetteur',
                           'size': 2,
                           'type': 'A',
                           'values': { 'AN': 'Assemblée nationale',
                                       'BF': 'Banque de france',
                                       'CC': 'Caisse des cultes',
                                       'CE': 'Caisse de retraite et de prévoyance des clercs et employés de notaires (CRPCEN)',
                                       'CF': 'SNCF',
                                       'CI': 'Chambre de commerce et d’industrie de paris',
                                       'CM': 'Caisse nationale militaire de sécurité sociale (CNMSS)',
                                       'CP': 'C.P.A.M.',
                                       'CR': 'C.R.A.M.',
                                       'CS': 'Centre de Service Complémentaire (AMC)',
                                       'CT': 'Centre de traitement informatique (Régime Général)',
                                       'EN': 'Établissement national des invalides de la marine (ENIM)',
                                       'MA': 'MSA',
                                       'OC': 'Organisme complémentaire (AMC)',
                                       'OT': 'Organisme concentrateur technique (OCT)',
                                       'PB': 'Port autonome de bordeaux',
                                       'RM': 'Sécurité sociale minière',
                                       'RP': 'R.A.T.P.',
                                       'SE': 'Caisses autonomes de sécurité sociale du senat',
                                       'SI': 'Autres émetteurs (sociétés civiles professionnelles...)',
                                       'SM': 'Section des mutuelles nationales',
                                       'SR': 'Centre informatique regional (AMPI)',
                                       'TE': 'Établissements',
                                       'TP': 'Autres partenaires de sante'}},
                         { 'name': "Numéro d'émetteur",
                           'order': 3,
                           'presence': 'O',
                           'size': 14,
                           'type': 'N'},
                         { 'name': 'Programme émetteur',
                           'order': 4,
                           'presence': 'F',
                           'size': 6,
                           'type': 'A'},
                         { 'name': 'Type de destinataire',
                           'order': 5,
                           'presence': 'O',
                           'size': 2,
                           'type': 'A',
                           'values': { 'AN': 'Assemblée nationale',
                                       'BF': 'Banque de france',
                                       'CC': 'Caisse des cultes',
                                       'CE': 'Caisse de retraite et de prévoyance des clercs et employés de notaires (CRPCEN)',
                                       'CF': 'SNCF',
                                       'CI': 'Chambre de commerce et d’industrie de paris',
                                       'CM': 'Caisse nationale militaire de securite sociale (CNMSS)',
                                       'CP': 'C.P.A.M.',
                                       'CR': 'C.R.A.M.',
                                       'CS': 'Centre de Service Complémentaire (AMC)',
                                       'CT': 'Centre de traitement informatique (Régime Général)',
                                       'EN': 'Établissement national des invalides de la marine (ENIM)',
                                       'MA': 'MSA',
                                       'OC': 'Organisme complémentaire (AMC)',
                                       'OT': 'Organisme concentrateur technique (OCT)',
                                       'PB': 'Port autonome de bordeaux',
                                       'RM': 'Sécurité sociale minière',
                                       'RP': 'R.A.T.P.',
                                       'SE': 'Caisses autonomes de sécurité sociale du senat',
                                       'SI': 'Autres émetteurs (sociétés civiles professionnelles...)',
                                       'SM': 'Section des mutuelles nationales',
                                       'SR': 'Centre informatique regional (AMPI)',
                                       'TE': 'Établissements',
                                       'TP': 'Autres partenaires de santé'}},
                         { 'name': 'Numéro de destinataire',
                           'order': 6,
                           'presence': 'O',
                           'size': 14,
                           'type': 'A'},
                         { 'name': 'Programme destinataire',
                           'order': 7,
                           'presence': 'F',
                           'size': 6,
                           'type': 'A'},
                         { 'name': "Application-type d'échange",
                           'order': 8,
                           'presence': 'F',
                           'size': 2,
                           'type': 'A'},
                         { 'name': 'Identification du fichier',
                           'order': 9,
                           'presence': 'O',
                           'size': 6,
                           'type': 'A'},
                         { 'name': 'Date de création du fichier',
                           'order': 10,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': "Norme utilisée - référence de l'échange",
                           'order': 11,
                           'presence': 'O',
                           'size': 4,
                           'type': 'A'},
                         { 'name': 'Version utilisée',
                           'order': 12,
                           'presence': 'F',
                           'size': 2,
                           'type': 'A'},
                         { 'name': 'Compactage',
                           'order': 13,
                           'presence': 'F',
                           'size': 1,
                           'type': 'A'},
                         { 'name': 'Cryptage',
                           'order': 14,
                           'presence': 'F',
                           'size': 1,
                           'type': 'A',
                           'values': {'N': 'Non', 'O': 'Oui'}},
                         { 'name': 'Unité monétaire',
                           'order': 15,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': {'U': 'Euro'}},
                         { 'name': 'Type de flux',
                           'order': 16,
                           'presence': 'F',
                           'size': 1,
                           'type': 'A',
                           'values': { ' ': 'Réel',
                                       'D': 'Démo',
                                       'R': 'Réel',
                                       'T': 'Test'}},
                         { 'name': 'Blanc',
                           'order': 17,
                           'presence': 'F',
                           'size': 11,
                           'type': 'A'},
                         { 'name': "Longueur d'enregistrement",
                           'order': 18,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Mot de passe',
                           'order': 19,
                           'presence': 'F',
                           'size': 6,
                           'type': 'A'},
                         { 'name': 'Zone message',
                           'order': 20,
                           'presence': 'F',
                           'size': 37,
                           'type': 'A'}]},
  '010': { 'description': 'Organisme complémentaire',
           'name': '010',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '010'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N',
                           'valeur': '01'},
                         { 'name': 'Numéro d\'organisme complémentaire',
                           'order': 4,
                           'presence': 'O',
                           'size': 7,
                           'type': 'N'},
                         { 'name': 'Clé du numéro d\'organisme complémentaire',
                           'order': 5,
                           'presence': 'O',
                           'size': 1,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 6,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '020': { 'description': 'Mandataire',
           'name': '020',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '020'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N',
                           'valeur': '01'},
                         { 'name': 'Numéro de destinataire de règlement',
                           'order': 3,
                           'presence': 'O',
                           'size': 15,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 4,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '040': { 'description': 'Destinataire de règlement',
           'name': '040',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '040'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N',
                           'valeur': '02'},
                         { 'name': 'Numéro de destinataire de règlement',
                           'order': 3,
                           'presence': 'O',
                           'size': 15,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 4,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '070': { 'description': 'Date comptable',
           'name': '070',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '070'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N',
                           'valeur': '02'},
                         { 'name': 'Date de la journée comptable',
                           'order': 3,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 4,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '071': { 'description': 'Date comptable et référence du virement',
           'name': '071',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '071'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N',
                           'valeur': '02'},
                         { 'name': "Date de la journée comptable ou date d'émission du virement",
                           'order': 3,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Libellé du virement - ligne 1',
                           'order': 4,
                           'presence': 'O',
                           'size': 32,
                           'type': 'A'},
                         { 'name': 'Libellé du virement - ligne 2',
                           'order': 5,
                           'presence': 'F',
                           'size': 32,
                           'type': 'A'},
                         { 'name': 'Organisme payeur',
                           'order': 6,
                           'presence': 'F',
                           'size': 10,
                           'type': 'A'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 7,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '080': { 'description': 'Lot',
           'name': '080',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '080'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Date de constitution du lot',
                           'order': 3,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Numéro de lot',
                           'order': 4,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 5,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '081': { 'description': 'Type de retour',
           'name': '081',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '081'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N',
                           'valeur': '02'},
                         { 'name': 'Code du type de retour',
                           'order': 3,
                           'presence': 'O',
                           'size': 2,
                           'type': 'N',
                           'values': { '01': 'Retours sur prestations transmises en flux électroniques',
                                       '02': 'Retours sur prestations en facturation papier',
                                       '03': 'Paiements ponctuels ou forfaitaires',
                                       '04': 'Rappels sur prestations',
                                       '05': 'Retenues'}},
                         { 'name': "Numéro du lieu d'éxecution de l'acte",
                           'order': 4,
                           'presence': 'F',
                           'size': 14,
                           'type': 'A'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 5,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '100': { 'description': 'Facture',
           'name': '100',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '100'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Numéro de facture',
                           'order': 3,
                           'presence': 'O',
                           'size': 9,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 4,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '102': { 'description': 'Facture',
           'name': '102',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '102'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'N° de facture',
                           'order': 3,
                           'presence': 'O',
                           'size': 9,
                           'type': 'A'},
                         { 'name': 'Complément au n° de facture',
                           'order': 4,
                           'presence': 'F',
                           'size': 6,
                           'type': 'A'},
                         { 'name': 'N° de lot',
                           'order': 5,
                           'presence': 'F',
                           'size': 3,
                           'type': 'A'},
                         { 'name': 'Date de création du lot',
                           'order': 6,
                           'presence': 'F',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Type de facture',
                           'order': 7,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': { 'A': 'Flux AMC',
                                       'B': 'Flux B2 ou SESAM dégradé',
                                       'C': 'Facture papier AMC',
                                       'D': 'DRE',
                                       'E': 'Rappel sur prestations',
                                       'F': 'FSE',
                                       'L': 'Reservé pour les échanges inter-centres de traitement - liquide',
                                       'P': 'Facture papier AMO ou AMO + AMC',
                                       'R': 'Reservé pour les échanges inter-centres de traitement - rejeté'}},
                         { 'name': 'Date de facturation',
                           'order': 8,
                           'presence': 'F',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Traitement effectué sur la part AMC',
                           'order': 9,
                           'presence': 'F',
                           'size': 1,
                           'type': 'A',
                           'values': { ' ': 'Pas de traitement de la part AMC',
                                       'A': 'Éclatement par un OCT',
                                       'C': 'Paiement coordonné (CMU, référent, noemie 3...)',
                                       'E': 'Éclatement sur le poste',
                                       'F': 'Éclatement par un OCT',
                                       'N': "Envoi de l'image décompte en noemie 1 suite à TP sur la part AMC",
                                       'V': 'Orde de virement distinct pour la part AMO et le part AMC'}},
                         { 'name': "Nature d'assurance",
                           'order': 10,
                           'presence': 'F',
                           'size': 2,
                           'type': 'A'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 11,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '103': { 'description': 'Assuré et bénéficiaire',
           'name': '103',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '103'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'N° immatriculation',
                           'order': 3,
                           'presence': 'O',
                           'size': 13,
                           'type': 'A'},
                         { 'name': "Clé du numéro d'immatriculation",
                           'order': 4,
                           'presence': 'O',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Nom patronymique',
                           'order': 5,
                           'presence': 'F',
                           'size': 25,
                           'type': 'A'},
                         { 'name': "Nom d'usage",
                           'order': 6,
                           'presence': 'F',
                           'size': 25,
                           'type': 'A'},
                         { 'name': 'Prénom',
                           'order': 7,
                           'presence': 'F',
                           'size': 15,
                           'type': 'A'},
                         { 'name': 'N° immatriculation individuel',
                           'order': 8,
                           'presence': 'F',
                           'size': 13,
                           'type': 'A'},
                         { 'name': "Clé du numéro d'immatriculation individuel",
                           'order': 9,
                           'presence': 'F',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Date de naissance',
                           'order': 10,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Rang de naissance',
                           'order': 11,
                           'presence': 'O',
                           'size': 1,
                           'type': 'N'},
                         { 'name': 'Nom',
                           'order': 12,
                           'presence': 'F',
                           'size': 25,
                           'type': 'A'},
                         { 'name': 'Prénom',
                           'order': 13,
                           'presence': 'F',
                           'size': 15,
                           'type': 'A'},
                         { 'name': 'Unité de gestion de rattachement',
                           'order': 14,
                           'presence': 'F',
                           'size': 4,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 15,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '110': { 'description': 'Assuré',
           'name': '110',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '110'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Numéro de sécurité sociale',
                           'order': 3,
                           'presence': 'O',
                           'size': 13,
                           'type': 'A'},
                         { 'name': 'Clé du numéro de sécurité sociale',
                           'order': 4,
                           'presence': 'O',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Nature du nom',
                           'order': 5,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': { 'M': 'Marital',
                                       'P': 'Patronymique',
                                       'U': 'Usage'}},
                         { 'name': 'Nom du bénéficiaire',
                           'order': 6,
                           'presence': 'O',
                           'size': 25,
                           'type': 'A'},
                         { 'name': 'Blanc',
                           'order': 7,
                           'presence': 'O',
                           'size': 26,
                           'type': 'A'},
                         { 'name': 'Prénom du bénéficiaire',
                           'order': 8,
                           'presence': 'O',
                           'size': 15,
                           'type': 'A'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 9,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '120': { 'description': 'Malade',
           'name': '120',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '120'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Date de naissance du bénéficiaire',
                           'order': 3,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Rang du bénéficiaire',
                           'order': 4,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A'},
                         { 'name': 'Nom du malade',
                           'order': 5,
                           'presence': 'O',
                           'size': 25,
                           'type': 'A'},
                         { 'name': 'Prénom du malade',
                           'order': 6,
                           'presence': 'O',
                           'size': 15,
                           'type': 'A'},
                         { 'name': 'Unité de gestion de rattachement',
                           'order': 7,
                           'presence': 'O',
                           'size': 4,
                           'type': 'A'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 9,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '150': { 'description': "Nature d'assurance",
           'name': '150',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '150'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': "Nature de l'assurance",
                           'order': 3,
                           'presence': 'O',
                           'size': 2,
                           'type': 'A',
                           'values': { 'AM': 'Maternité',
                                       'AS': 'Maladie',
                                       'AT': 'Accident du travail'}},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 4,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '160': { 'description': "Critère d'archivage",
           'name': '160',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '160'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': "Numéro d'archivage",
                           'order': 3,
                           'presence': 'O',
                           'size': 17,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 4,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '198': { 'description': 'Part AMO',
           'name': '198',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '198'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Montant AMO demandé',
                           'order': 3,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'État paiement part AMO',
                           'order': 4,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': { ' ': 'Pas de traitement de cette part',
                                       'D': 'Differé',
                                       'P': 'Payé',
                                       'R': 'Rejeté'}},
                         { 'name': 'Montant AMO payé',
                           'order': 5,
                           'presence': 'F',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Signe du montant AMO payé',
                           'order': 6,
                           'presence': 'O',
                           'size': 1,
                           'type': 'N',
                           'values': {'N': 'Négatif', 'P': 'Positif'}},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 7,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '199': { 'description': 'Part AMC',
           'name': '199',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '199'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Montant AMC demandé',
                           'order': 3,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'État paiement part AMC',
                           'order': 4,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': { ' ': 'Pas de traitement de cette part',
                                       'D': 'Differé',
                                       'P': 'Payé',
                                       'R': 'Rejeté'}},
                         { 'name': 'Montant AMC payé',
                           'order': 5,
                           'presence': 'F',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Signe du montant AMC payé',
                           'order': 6,
                           'presence': 'O',
                           'size': 1,
                           'type': 'N',
                           'values': {'N': 'Négatif', 'P': 'Positif'}},
                         { 'name': 'N° AMC destinataire',
                           'order': 7,
                           'presence': 'O',
                           'size': 10,
                           'type': 'N'},
                         { 'name': "N° identification AMC de l'adhérent",
                           'order': 8,
                           'presence': 'F',
                           'size': 15,
                           'type': 'A'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 9,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '210': { 'description': 'Acte professionnel',
           'name': '210',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '210'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'N° de ligne',
                           'order': 3,
                           'presence': 'O',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Code gestion technique pour régime',
                           'order': 4,
                           'presence': 'O',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Justification pour exonération',
                           'order': 5,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A'},
                         { 'name': 'Mode de traitement',
                           'order': 6,
                           'presence': 'O',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Discipline médico-tarifaire',
                           'order': 7,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': "Date de prescription d'un acte",
                           'order': 8,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Date des soins ou date début',
                           'order': 9,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Date de fin de soins',
                           'order': 10,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': "Prix unitaire d'un acte",
                           'order': 11,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': "Base de remboursement d'un acte",
                           'order': 12,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Taux de remboursement',
                           'order': 13,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Montant remboursé',
                           'order': 14,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': "Signe de l'acte",
                           'order': 15,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': {'N': 'Négatif', 'P': 'Positif'}},
                         { 'name': 'Nature de la prestation',
                           'order': 16,
                           'presence': 'O',
                           'size': 3,
                           'type': 'A'},
                         { 'name': "Code complémentaire à la nature d'acte",
                           'order': 17,
                           'presence': 'O',
                           'size': 2,
                           'type': 'A',
                           'values': { 'E': 'Examen, expertise',
                                       'F': 'Majoration jour férié',
                                       'N': 'Majoration de nuit',
                                       'P': 'Présent',
                                       'S': 'Sortie',
                                       'T': 'Transfert'}},
                         { 'name': "Quantité d'actes",
                           'order': 18,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': "Coefficient de l'acte",
                           'order': 19,
                           'presence': 'O',
                           'size': 5,
                           'type': 'N'},
                         { 'name': 'Dénombrement des actes',
                           'order': 20,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Montant de la dépense',
                           'order': 21,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Qualificatif de la dépense',
                           'order': 22,
                           'presence': 'O',
                           'size': 2,
                           'type': 'A',
                           'values': { 'AT': 'Tiers payant AT',
                                       'DD': 'Dépassement non prescrit',
                                       'DE': 'Dépassement exigence',
                                       'DF': 'Dépassement Fortune',
                                       'DP': 'Dépassement permanent',
                                       'ED': 'Entente directe',
                                       'GR': 'Gratuit',
                                       'NR': 'Non remboursabe',
                                       'S': 'Honoraire globalisés, suite',
                                       'TM': 'Ticket modérateur seul'}},
                         { 'name': 'Taux complémentaire Alsace/Moselle',
                           'order': 23,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Montant complémentaire Alsace/Moselle',
                           'order': 24,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Taux part complémentaire Mutuelle',
                           'order': 25,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Montant part complémentaire',
                           'order': 26,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Base remboursement Mutuelle',
                           'order': 27,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 28,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '220': { 'description': 'Frais hospitaliers',
           'name': '220',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '220'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'N° de ligne',
                           'order': 3,
                           'presence': 'O',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Code gestion technique pour régime',
                           'order': 4,
                           'presence': 'O',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Justification pour exonération',
                           'order': 5,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A'},
                         { 'name': 'Mode de traitement',
                           'order': 6,
                           'presence': 'O',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Discipline médico-tarifaire',
                           'order': 7,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Date des soins ou date début',
                           'order': 9,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Date de fin de soins',
                           'order': 10,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': "Prix unitaire d'un acte",
                           'order': 11,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': "Base de remboursement d'un acte",
                           'order': 12,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Taux de remboursement',
                           'order': 13,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Montant remboursé',
                           'order': 14,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': "Signe de l'acte",
                           'order': 15,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': {'N': 'Négatif', 'P': 'Positif'}},
                         { 'name': 'Nature de la prestation',
                           'order': 16,
                           'presence': 'O',
                           'size': 3,
                           'type': 'A'},
                         { 'name': "Code complémentaire à la nature d'acte",
                           'order': 17,
                           'presence': 'O',
                           'size': 2,
                           'type': 'A',
                           'values': { 'E': 'Examen, expertise',
                                       'F': 'Majoration jour férié',
                                       'N': 'Majoration de nuit',
                                       'P': 'Présent',
                                       'S': 'Sortie',
                                       'T': 'Transfert'}},
                         { 'name': "Quantité d'actes",
                           'order': 18,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': "Coefficient de l'acte",
                           'order': 19,
                           'presence': 'O',
                           'size': 5,
                           'type': 'N'},
                         { 'name': 'Dénombrement des actes',
                           'order': 20,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Montant de la dépense',
                           'order': 21,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Qualificatif de la dépense',
                           'order': 22,
                           'presence': 'O',
                           'size': 2,
                           'type': 'A',
                           'values': { 'AT': 'Tiers payant AT',
                                       'DD': 'Dépassement non prescrit',
                                       'DE': 'Dépassement exigence',
                                       'DF': 'Dépassement Fortune',
                                       'DP': 'Dépassement permanent',
                                       'ED': 'Entente directe',
                                       'GR': 'Gratuit',
                                       'NR': 'Non remboursabe',
                                       'S': 'Honoraire globalisés, suite',
                                       'TM': 'Ticket modérateur seul'}},

                         { 'name': "Coefficient global pour hospitalisation",
                           'order': 22,
                           'presence': 'O',
                           'size': 5,
                           'type': 'N'},
                         { 'name': "Code forfait à générer",
                           'order': 22,
                           'presence': 'O',
                           'size': 1,
                           'type': 'N'},

                         { 'name': 'Taux complémentaire Alsace/Moselle',
                           'order': 23,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Montant complémentaire Alsace/Moselle',
                           'order': 24,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Taux part complémentaire Mutuelle',
                           'order': 25,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Montant part complémentaire',
                           'order': 26,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Base remboursement Mutuelle',
                           'order': 27,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 28,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},

  '250': { 'description': 'Mouvement financier - retenue',
           'name': '250',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '250'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Numéro de ligne pour noemie',
                           'order': 3,
                           'presence': 'O',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Référence de la dette',
                           'order': 4,
                           'presence': 'O',
                           'size': 10,
                           'type': 'A'},
                         { 'name': "Date d'enregistrement de la dette",
                           'order': 5,
                           'presence': 'O',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Nature de la dette',
                           'order': 6,
                           'presence': 'O',
                           'size': 3,
                           'type': 'A',
                           'values': { 'ACC': 'Accompte sur prestations',
                                       'AFF': 'Affranchissement',
                                       'API': 'Acompte caisse centralisatrice des paiements',
                                       'APR': 'Avance sur prestations',
                                       'IEC': 'Indui suite à erreur comptable',
                                       'IND': 'Indu sur prestations',
                                       'IPH': 'Indu sur avance pharmacie',
                                       'IPI': 'Créance non gérée par caisse gestionnaire',
                                       'ISP': 'Impayé mandat ou virement solde',
                                       'ODL': 'Opposition interne paiement en double',
                                       'OID': 'Opposition interne diverse',
                                       'REL': 'Reliquat',
                                       'VMI': 'Virement ou mandat impayé'}},
                         { 'name': 'Nature des opérations de récupération',
                           'order': 7,
                           'presence': 'O',
                           'size': 3,
                           'type': 'A',
                           'values': { 'ANT': 'Annulation totale',
                                       'CIN': 'Constat initial',
                                       'LOP': "Main levée d'opposition partielle",
                                       'LOT': "Main levée d'opposition totale",
                                       'NVP': 'Admission en non valeur partielle',
                                       'NVT': 'Admission en non valeur totale',
                                       'PAI': 'Paiement',
                                       'PPR': 'Passage en profit',
                                       'RAS': "Remboursement à l'assuré",
                                       'RDP': 'Remise de dette partielle',
                                       'RDS': 'Remise de dette < seuil',
                                       'RDT': 'Remise de dette totale',
                                       'REL': "Rectification d'un élement signalétique",
                                       'RMO': "Rectification d'un montant",
                                       'RPR': 'Retenue sur prestation'}},
                         { 'name': 'Montant du mouvement financier',
                           'order': 8,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': "Signe de l'acte",
                           'order': 9,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': {'N': 'Négatif', 'P': 'Positif'}},
                         { 'name': "Montant du solde d'une dette",
                           'order': 10,
                           'presence': 'F',
                           'size': 8,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 11,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '261': { 'description': 'Paiements ponctuels ou forfaitaires',
           'name': '261',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '261'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Code paiement ponctuel ou forfaitaire',
                           'order': 3,
                           'presence': 'O',
                           'size': 5,
                           'type': 'N'},
                         { 'name': 'Montant paiment ponctuel ou forfaitaire',
                           'order': 4,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 5,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '262': { 'description': 'Détail paiement ponctuel ou forfaitaire',
           'name': '262',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '262'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Codification',
                           'order': 3,
                           'presence': 'F',
                           'size': 5,
                           'type': 'A'},
                         { 'name': 'Libellé associé',
                           'order': 4,
                           'presence': 'F',
                           'size': 80,
                           'type': 'A'},
                         { 'name': "N° d'immatriculation",
                           'order': 5,
                           'presence': 'F',
                           'size': 13,
                           'type': 'A'},
                         { 'name': "Clé du numéro d'immatriculation",
                           'order': 6,
                           'presence': 'F',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Date de naissance',
                           'order': 7,
                           'presence': 'F',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Rang de naissance',
                           'order': 8,
                           'presence': 'F',
                           'size': 1,
                           'type': 'N'},
                         { 'name': 'Période',
                           'order': 9,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': { 'A': 'Annuel',
                                       'H': 'Hebdo',
                                       'M': 'Mensuel',
                                       'P': 'Ponctuel',
                                       'S': 'Semestriel',
                                       'T': 'Trimestriel'}},
                         { 'name': 'Date début période',
                           'order': 10,
                           'presence': 'F',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Date fin période',
                           'order': 11,
                           'presence': 'F',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'Montant',
                           'order': 12,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 13,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '290': { 'description': 'Rejet ou signalement',
           'name': '290',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '290'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'N° de ligne',
                           'order': 3,
                           'presence': 'O',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Codification',
                           'order': 4,
                           'presence': 'O',
                           'size': 10,
                           'type': 'A'},
                         { 'name': 'Libellé',
                           'order': 5,
                           'presence': 'O',
                           'size': 80,
                           'type': 'A'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 7,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '294': { 'description': 'Ligne rejet',
           'name': '294',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '294'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Codification du rejet',
                           'order': 3,
                           'presence': 'O',
                           'size': 4,
                           'type': 'A'},
                         { 'name': 'Libellé du rejet',
                           'order': 4,
                           'presence': 'O',
                           'size': 86,
                           'type': 'A'},
                         { 'name': 'Niveau de rejet',
                           'order': 5,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': { 'A': 'Code affiné',
                                       'F': 'Facture',
                                       'L': 'Ligne de prestation'}},
                         { 'name': 'Part concerné',
                           'order': 6,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': { 'C': 'Part complémentaire',
                                       'O': 'Part obligatoire ou part obligatoire + complémentaire'}},
                         { 'name': 'Nature de prestation concernée',
                           'order': 7,
                           'presence': 'F',
                           'size': 5,
                           'type': 'A'},
                         { 'name': 'Date des soins',
                           'order': 8,
                           'presence': 'F',
                           'size': 6,
                           'type': 'N'},
                         { 'name': 'N° exécutant',
                           'order': 9,
                           'presence': 'F',
                           'size': 9,
                           'type': 'N'},
                         { 'name': 'N° de ligne',
                           'order': 10,
                           'presence': 'F',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Rang du rejet',
                           'order': 11,
                           'presence': 'F',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Information complémentaire sur le rejet',
                           'order': 12,
                           'presence': 'F',
                           'size': 30,
                           'type': 'A'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 13,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '295': { 'description': 'Ligne commentaire',
           'name': '295',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '295'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N'},
                         { 'name': 'Code commentaire',
                           'order': 3,
                           'presence': 'F',
                           'size': 1,
                           'type': 'A'},
                         { 'name': 'Commentaire',
                           'order': 4,
                           'presence': 'O',
                           'size': 128,
                           'type': 'A'},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 5,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '990': { 'description': 'Entité de contrôle',
           'name': '990',
           'rang': '2',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '990'},
                         { 'name': 'Niveau de rupture',
                           'order': 2,
                           'presence': 'O',
                           'saveas': 'rang',
                           'size': 2,
                           'type': 'N',
                           'valeur': '99'},
                         { 'name': 'Identification du niveau de rupture',
                           'order': 3,
                           'presence': 'F',
                           'size': 17,
                           'type': 'A'},
                         { 'name': 'Compteur du niveau inférieur dans la hierarchie',
                           'order': 4,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Cumul des montants de niveau inférieur',
                           'order': 5,
                           'presence': 'O',
                           'size': 11,
                           'type': 'N'},
                         { 'name': "Signe de l'acte",
                           'order': 6,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': {'N': 'Négatif', 'P': 'Positif'}},
                         { 'name': "Délimiteur fin d'entité",
                           'order': 7,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'valeur': '@'}]},
  '999': { 'description': 'Fin de fichier',
           'name': '999',
           'rang': '1',
           'segments': [ { 'name': "Type d'enregistrement",
                           'order': 1,
                           'pkey': 'O',
                           'presence': 'O',
                           'size': 3,
                           'type': 'N',
                           'valeur': '999'},
                         { 'name': "Type d'émetteur",
                           'order': 2,
                           'presence': 'O',
                           'size': 2,
                           'type': 'A',
                           'values': { 'AN': 'ASSEMBLEE NATIONALE',
                                       'BF': 'BANQUE DE FRANCE',
                                       'CC': 'CAISSE DES CULTES',
                                       'CE': 'CAISSE DE RETRAITE ET DE PREVOYANCE DES CLERCS ET EMPLOYES DE NOTAIRES (CRPCEN)',
                                       'CF': 'SNCF',
                                       'CI': 'CHAMBRE DE COMMERCE ET D’INDUSTRIE DE PARIS',
                                       'CM': 'CAISSE NATIONALE MILITAIRE DE SECURITE SOCIALE (CNMSS)',
                                       'CP': 'C.P.A.M.',
                                       'CR': 'C.R.A.M.',
                                       'CS': 'Centre de Service Complémentaire (AMC)',
                                       'CT': 'CENTRE DE TRAITEMENT INFORMATIQUE (Régime Général)',
                                       'EN': 'ETABLISSEMENT NATIONAL DES INVALIDES DE LA MARINE (ENIM)',
                                       'MA': 'MSA',
                                       'OC': 'Organisme Complémentaire (AMC)',
                                       'OT': 'ORGANISME CONCENTRATEUR TECHNIQUE (OCT)',
                                       'PB': 'PORT AUTONOME DE BORDEAUX',
                                       'RM': 'SECURITE SOCIALE MINIERE',
                                       'RP': 'R.A.T.P.',
                                       'SE': 'CAISSES AUTONOMES DE SECURITE SOCIALE DU SENAT',
                                       'SI': 'AUTRES EMETTEURS (Sociétés civiles professionnelles...)',
                                       'SM': 'SECTION DES MUTUELLES NATIONALES',
                                       'SR': 'CENTRE INFORMATIQUE REGIONAL (AMPI)',
                                       'TE': 'ETABLISSEMENTS',
                                       'TP': 'AUTRES PARTENAIRES DE SANTE'}},
                         { 'name': "Numéro d'émetteur",
                           'order': 3,
                           'presence': 'O',
                           'size': 14,
                           'type': 'N'},
                         { 'name': 'Programme émetteur',
                           'order': 4,
                           'presence': 'F',
                           'size': 6,
                           'type': 'A'},
                         { 'name': 'Type de destinataire',
                           'order': 5,
                           'presence': 'O',
                           'size': 2,
                           'type': 'A',
                           'values': { 'AN': 'ASSEMBLEE NATIONALE',
                                       'BF': 'BANQUE DE FRANCE',
                                       'CC': 'CAISSE DES CULTES',
                                       'CE': 'CAISSE DE RETRAITE ET DE PREVOYANCE DES CLERCS ET EMPLOYES DE NOTAIRES (CRPCEN)',
                                       'CF': 'SNCF',
                                       'CI': 'CHAMBRE DE COMMERCE ET D’INDUSTRIE DE PARIS',
                                       'CM': 'CAISSE NATIONALE MILITAIRE DE SECURITE SOCIALE (CNMSS)',
                                       'CP': 'C.P.A.M.',
                                       'CR': 'C.R.A.M.',
                                       'CS': 'Centre de Service Complémentaire (AMC)',
                                       'CT': 'CENTRE DE TRAITEMENT INFORMATIQUE (Régime Général)',
                                       'EN': 'ETABLISSEMENT NATIONAL DES INVALIDES DE LA MARINE (ENIM)',
                                       'MA': 'MSA',
                                       'OC': 'Organisme Complémentaire (AMC)',
                                       'OT': 'ORGANISME CONCENTRATEUR TECHNIQUE (OCT)',
                                       'PB': 'PORT AUTONOME DE BORDEAUX',
                                       'RM': 'SECURITE SOCIALE MINIERE',
                                       'RP': 'R.A.T.P.',
                                       'SE': 'CAISSES AUTONOMES DE SECURITE SOCIALE DU SENAT',
                                       'SI': 'AUTRES EMETTEURS (Sociétés civiles professionnelles...)',
                                       'SM': 'SECTION DES MUTUELLES NATIONALES',
                                       'SR': 'CENTRE INFORMATIQUE REGIONAL (AMPI)',
                                       'TE': 'ETABLISSEMENTS',
                                       'TP': 'AUTRES PARTENAIRES DE SANTE'}},
                         { 'name': 'Numéro de destinataire',
                           'order': 6,
                           'presence': 'O',
                           'size': 14,
                           'type': 'A'},
                         { 'name': 'Programme destinataire',
                           'order': 7,
                           'presence': 'F',
                           'size': 6,
                           'type': 'A'},
                         { 'name': "Application-type d'échange",
                           'order': 8,
                           'presence': 'F',
                           'size': 2,
                           'type': 'A'},
                         { 'name': 'Identification du fichier',
                           'order': 9,
                           'presence': 'O',
                           'size': 6,
                           'type': 'A'},
                         { 'name': "Nombre d'enregistrements",
                           'order': 10,
                           'presence': 'O',
                           'size': 8,
                           'type': 'N'},
                         { 'name': 'Type de flux',
                           'order': 11,
                           'presence': 'F',
                           'size': 1,
                           'type': 'A',
                           'values': { ' ': 'Réel',
                                       'D': 'Démo',
                                       'R': 'Réel',
                                       'T': 'Test'}},
                         { 'name': 'Blanc',
                           'order': 12,
                           'presence': 'F',
                           'size': 18,
                           'type': 'A'},
                         { 'name': 'Nombre de lots',
                           'order': 13,
                           'presence': 'O',
                           'size': 3,
                           'type': 'N'},
                         { 'name': 'Cumul des montants du fichier',
                           'order': 14,
                           'presence': 'O',
                           'size': 11,
                           'type': 'N'},
                         { 'name': 'Signe du montant du fichier',
                           'order': 15,
                           'presence': 'O',
                           'size': 1,
                           'type': 'A',
                           'values': {'N': 'Négatif', 'P': 'Positif'}},
                         { 'name': "Cumul des montants du fichier dans l'autre monnaie",
                           'order': 16,
                           'presence': 'F',
                           'size': 11,
                           'type': 'N'},
                         { 'name': 'Blanc',
                           'order': 17,
                           'presence': 'F',
                           'size': 20,
                           'type': 'A'}]}}
