LAST_DUMP=20121221-192258

DUMP=dump-$(LAST_DUMP).tar.bz2

all:
	wget --no-check-certificate https://dav.entrouvert.org/Clients%20et%20contacts/Clients%20en%20cours/APS42/Import/$(DUMP)
	tar xvjf $(DUMP)
