# -*- coding: utf-8 -*-
'''
    The state name is for instance the string 'CMPP_STATE_ACCUEIL'
    The value given in the dictionnary can only be used for display.
'''

# CMPP States
CMPP_STATE_ACCUEIL = "En contact"
CMPP_STATE_FIN_ACCUEIL = "Fin d'accueil"
CMPP_STATE_DIAGNOSTIC = "Diagnostic"
CMPP_STATE_TRAITEMENT = "Traitement"
CMPP_STATE_CLOS = "Clos"
CMPP_STATES = {'CMPP_STATE_ACCUEIL': CMPP_STATE_ACCUEIL,
    'CMPP_STATE_FIN_ACCUEIL': CMPP_STATE_FIN_ACCUEIL,
    'CMPP_STATE_DIAGNOSTIC': CMPP_STATE_DIAGNOSTIC,
    'CMPP_STATE_TRAITEMENT': CMPP_STATE_TRAITEMENT,
    'CMPP_STATE_CLOS': CMPP_STATE_CLOS}

# CAMSP States
CAMSP_STATE_ACCUEIL = "En contact"
CAMSP_STATE_FIN_ACCUEIL = "Fin d'accueil"
CAMSP_STATE_BILAN = "Bilan"
CAMSP_STATE_SURVEILLANCE = "Surveillance"
CAMSP_STATE_SUIVI = "Suivi"
CAMSP_STATE_CLOS = "Clos"
CAMSP_STATES = {'CAMSP_STATE_ACCUEIL': CAMSP_STATE_ACCUEIL,
    'CAMSP_STATE_FIN_ACCUEIL': CAMSP_STATE_FIN_ACCUEIL,
    'CAMSP_STATE_BILAN': CAMSP_STATE_BILAN,
    'CAMSP_STATE_SURVEILLANCE': CAMSP_STATE_SURVEILLANCE,
    'CAMSP_STATE_SUIVI': CAMSP_STATE_SUIVI,
    'CAMSP_STATE_CLOS': CAMSP_STATE_CLOS}

# SESSAD States
SESSAD_STATE_ACCUEIL = "En contact"
SESSAD_STATE_FIN_ACCUEIL = "Fin d'accueil"
SESSAD_STATE_TRAITEMENT = "Traitement"
SESSAD_STATE_CLOS = "Clos"
SESSAD_STATES = {'SESSAD_STATE_ACCUEIL': SESSAD_STATE_ACCUEIL,
    'SESSAD_STATE_FIN_ACCUEIL': SESSAD_STATE_FIN_ACCUEIL,
    'SESSAD_STATE_TRAITEMENT': SESSAD_STATE_TRAITEMENT,
    'SESSAD_STATE_CLOS': SESSAD_STATE_CLOS}

STATES = {'CMPP' : CMPP_STATES,
    'CAMSP': CAMSP_STATES,
    'SESSAD': SESSAD_STATES}

STATE_ACCUEIL = {'CMPP' : 'CMPP_STATE_ACCUEIL',
    'CAMSP': 'CAMSP_STATE_ACCUEIL',
    'SESSAD': 'SESSAD_STATE_ACCUEIL'}

STATES_MAPPING = dict(CMPP_STATES, **CAMSP_STATES)
STATES_MAPPING = dict(STATES_MAPPING, **SESSAD_STATES)

